### ISSUE TITLE
Shrinkpack currently requires global install

### ISSUE THREAD

**Issue by jeremyhofman** [jeremyhofman/grunt-shrinkpack#1]
Shrinkpack currently needs to be installed globally for grunt-shrinkpack to work. Need to fix it to check for a global installation is found; if not, call shrinkpack.cmd from the node_modules/.bin folder within the project.

**Comment by JamieMason** [comment]
Thanks for creating this @jeremyhofman, 
I should document this in the README, but it is possible to call `shrinkpack` from within node. 

## 1. Node API

Shrinkpack works in 2 phases;
1. Analyse the project and gather all the diffing information between the file system and the shrinkwrap.
2. Use the diffing information to bring the file system in sync with the shrinkwrap.

``` js
var shrinkpack = require('shrinkpack');

shrinkpack.analyse({
  compress: false,
  directory: process.cwd(),
  keepOptional: false
}).then(function (data) {
  shrinkpack.update(data);
});
```

## 2. Internal API for the CLI

This approach does the same as the above, but also writes out all the additional logging that you see when using `shrinkpack` normally.

``` js
var cli = require('shrinkpack/src/cli');

cli.run({
  compress: false,
  directory: process.cwd(),
  keepOptional: false
});
```

Hope this helps, thanks a lot.

**Comment by jeremyhofman** [comment]
Ah cool - I missed that when I was looking through the best way to implement this.  I'll definitely give this approach a try (and update accordingly).  I spent too much time on Friday trying to make sure I didn't break the grunt process for Mac users...your CLI approach does that without intervention!

Thanks!

**Comment by jeremyhofman** [comment]
Modified this in 0.0.4 to use the pwd to run the task.  Will change to use Jamie's native CLI in a future version.
